stages:
  - deploy

cache:
  paths:
  - .apt/

deploy:
  stage: deploy
  image: alpine:3.7
  script:
  - apk update && apk add git
  - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
  only:
    refs:
    - master